apiVersion: v1
kind: Service
metadata:
  labels:
    job: node-api
    app: prometheus-service
  name: prometheus-service
spec:
  ports:
  - name: prometheus-service-port
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: prometheus-deployment
  type: LoadBalancer

